name: ar_core
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  arcore_flutter_plugin:
    path: C:/Users/Dell/Downloads/arcore_flutter_plugin-master/arcore_flutter_plugin-master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
